products/urls.py
from django.urls import path
from . import views
import threading


urlpatterns = [
    # path('', views.ProductListView.as_view(), name='product_list'),
    path('', views.product_list, name='product_list'),
    path('product/add/', views.add_product, name='add_product'),
    path('product/delete/<int:pk>/', views.delete_product, name='delete_product'),
    path('product/block/<int:pk>/', views.block_user_and_delete_products, name='block_product'),
    path('start_bot/', views.start_bot_view, name='start_bot'),
    path('rules/', views.rules_view, name='rules'),
]





# import asyncio

# loop = asyncio.get_event_loop()
# loop.run_until_complete(b.run_bot())

tgta_marketplace/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('products.urls', 'products'), namespace='products')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/models.py
from datetime import timedelta
from django.conf import settings
from django.dispatch import receiver
from django.utils import timezone
from django.db import models
import telegram
from django.db.models.signals import post_save

class Server(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class Blocklist(models.Model):
    reason = models.CharField(max_length=64)
    ip = models.GenericIPAddressField()
    time_created = models.DateTimeField(auto_now_add=True)
    def __str__(self) -> str:
        return f'{self.reason} || {self.ip}'
    
class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    photo = models.ImageField(upload_to='product_photos')
    price = models.IntegerField()
    nickname = models.CharField(max_length=255)
    server = models.ForeignKey(Server, on_delete=models.CASCADE)
    ip_address = models.GenericIPAddressField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
    @staticmethod
    def get_products_by_server_and_name_filter(server, name_filter):
        products = Product.objects.filter(server=server)
        if name_filter:
            products = products.filter(models.Q(name__icontains=name_filter) | models.Q(description__icontains=name_filter))
        return products
    
    def filter_product(self, server, name_filter):
        if self.server == server:
            if name_filter == 'skip' or None:
                return True
            if not name_filter in self.name:
                return False
            return True
        return False
    

class BotUser(models.Model):
    telegram_id = models.CharField(max_length=50, unique=True)
    server = models.ForeignKey(Server, on_delete=models.SET_NULL, null=True)
    name_filter = models.CharField(max_length=100, blank=True, null=True)
    sent_products = models.ManyToManyField(Product, blank=True)

    def __str__(self):
        return f"{self.telegram_id}"

    def add_sent_product(self, product):
        self.sent_products.add(product)
        self.save()

    def set_selected_server(self, server):
        self.server = server
        self.save()

    def set_name_filter(self, name_filter):
        self.name_filter = name_filter
        self.save()
        
    def get_new_products_by_filter(self):
        five_hours_ago = timezone.now() - timedelta(hours=5)
        products = Product.get_products_by_server_and_name_filter(
            server=self.server,
            name_filter=self.name_filter,
        )
        new_products = products.exclude(id__in=self.sent_products.all())
        new_products = new_products.filter(created_at__gte=five_hours_ago)
        return new_products

products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'photo', 'price', 'nickname', 'server']
    
    widgets = {
        'name': forms.TextInput(attrs={'class': 'form-control'}),
        'description': forms.Textarea(attrs={'class': 'form-control'}),
        'price': forms.NumberInput(attrs={'class': 'form-control'}),
        'nickname': forms.TextInput(attrs={'class': 'form-control'}),
        'server': forms.Select(attrs={'class': 'form-control'})
    }

products/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ProductForm
from .models import Product, Blocklist
from django.contrib import messages
from django.views.generic import ListView
from django.db import models
from django.core.paginator import Paginator
import threading
from products.tasks import start_bot
from django.conf import settings


def get_user_ip(request):
    forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    return forwarded_for.split(',')[-1].strip() if forwarded_for else request.META.get('REMOTE_ADDR')

# def product_list(request):
#     products = Product.objects.all()
#     return render(request, 'products/product_list.html', {'products': products, 'ip': request.META.get('REMOTE_ADDR')})

def product_list(request):
    products = Product.objects.all()
    

    server = request.GET.get('server', None)
    name_or_description = request.GET.get('name_or_description', '')
    min_price = request.GET.get('min_price', None)
    max_price = request.GET.get('max_price', None)

    if server:
        products = products.filter(server__name=server)

    if name_or_description:
        products = products.filter(
            models.Q(name__icontains=name_or_description) |
            models.Q(description__icontains=name_or_description)
        )

    if min_price and max_price:
        products = products.filter(price__range=(min_price, max_price))
    elif min_price:
        products = products.filter(price__gte=min_price)
    elif max_price:
        products = products.filter(price__lte=max_price)

    products = products.order_by('price')
    
    paginator = Paginator(products, 5)
    page = request.GET.get('page')
    products = paginator.get_page(page)
    
    context = {
        'products': products,
        'ip': get_user_ip(request=request),
        'admin_ip': settings.ADMIN_IP,
        'filters': {
            'min_price': min_price, 
            'max_price': max_price, 
            'name_or_description': name_or_description,
            'server': server
        }
    }
    return render(request, 'products/product_list.html', context)

class ProductListView(ListView):
    model = Product
    template_name = 'product_list.html'
    context_object_name = 'products'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        server = self.request.GET.get('server', None)
        name_or_description = self.request.GET.get('name_or_description', None)
        min_price = self.request.GET.get('min_price', None)
        max_price = self.request.GET.get('max_price', None)

        if server:
            queryset = queryset.filter(server__name=server)

        if name_or_description:
            queryset = queryset.filter(
                models.Q(name__icontains=name_or_description) |
                models.Q(description__icontains=name_or_description)
            )

        if min_price and max_price:
            queryset = queryset.filter(price__range=(min_price, max_price))
        elif min_price:
            queryset = queryset.filter(price__gte=min_price)
        elif max_price:
            queryset = queryset.filter(price__lte=max_price)

        return queryset.order_by('price')

def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.ip_address = get_user_ip(request=request)
            product.save()
            return redirect('products:product_list')
    else:
        form = ProductForm()

    return render(request, 'products/add_product.html', {'form': form})

def delete_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if product.ip_address == get_user_ip(request=request):
        product.delete()
        messages.success(request, 'Товар удален.')
    else:
        messages.error(request, 'Вы не можете удалить.')
    return redirect('products:product_list')

def block_user_and_delete_products(request, pk):
    if settings.ADMIN_IP != get_user_ip(request=request):
        print("Ошибка бана")
        messages.error(request, 'Вы не можете удалить.')
        return redirect('products:product_list')
    product_base = get_object_or_404(Product, pk=pk)
    products = Product.objects.filter(ip_address=product_base.ip_address)
    for product in products:
        product.delete()
    bl = Blocklist(ip=product_base.ip_address, reason='Remove content')
    bl.save()
    messages.success(request, 'Пользователь заблокирован')
    return redirect('products:product_list')


# def start_bot():
#     bot_thread = threading.Thread(target=b.run_bot)
#     bot_thread.start()
    
def start_bot_view(request):
    start_bot.apply_async()
    return HttpResponse(status=200)

def rules_view(request):
    return render(request, 'products/rules.html')

products/templates/products/add_product.html
<!DOCTYPE html>
<html>
<head>
    <title>Добавление товара</title>
</head>
<body>
    <h1>Добавление товара</h1>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить</button>
    </form>

    <a href="{% url 'products:product_list' %}">Назад к списку товаров</a>
</body>
</html>

products/templates/products/product_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Список товаров | TGTA Marketplace</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" integrity="sha384-OaJzSjv7wk+OJ8XV7Olyjnjh4dVJa/+ZGnc1LpC/ytCxzK7V50PNOHdQP7Vh1Kj2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-jxzt0s3cKlCUYezxlT62mXgF2Q0ktcdRLqcJrQ0ff0D/8NU/PhwhJJDpky0nKj9X0eYYnwNvquzD29SvpWyS5w==" crossorigin="anonymous" />
    <style>
        body.light {
            background-color: #f8f9fa;
            color: #343a40;
        }
          
        body.dark {
            background-color: #343a40;
            color: #f8f9fa;
        }
        .light .card {
            background-color: #fff;
            border-color: #ddd;
            color: #333;
          }
          
          .dark .card {
            background-color: #222;
            border-color: #444;
            color: #fff;
          }
    </style>  
</head>
<body class='light mx-3 my-3'>
    {% comment %} <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="#">Dark Mode Switch</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <div class="custom-control custom-switch">
                  <input type="checkbox" class="custom-control-input" id="darkSwitch" />
                  <label class="custom-control-label" for="darkSwitch">Dark Mode</label>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav> {% endcomment %}
    <form class="mb-1" method="get" action="{% url 'products:product_list' %}">
        <div class="row">
          <div class="col-sm-2">
            <label for="server" class="form-label">Сервер:</label>
            <select name="server" id="server" class="form-select">
              <option value="">All</option>
              <option value="RP1" {% if filters.server == 'RP1' %}selected{% endif %}>RP1</option>
              <option value="RP2" {% if filters.server == 'RP2' %}selected{% endif %}>RP2</option>
              <option value="RPG" {% if filters.server == 'RPG' %}selected{% endif %}>RPG</option>
            </select>
          </div>
          <div class="col-sm-4">
            <label for="name_or_description" class="form-label">Поиск:</label>
            <input type="text" name="name_or_description" id="name_or_description" value="{{ filters.name_or_description }}" class="form-control">
          </div>
          <div class="col-sm-2">
            <label for="min_price" class="form-label">Мин. цена:</label>
            <input type="number" name="min_price" id="min_price" value="{{ filters.min_price }}" class="form-control">
          </div>
          <div class="col-sm-2">
            <label for="max_price" class="form-label">Макс. цена:</label>
            <input type="number" name="max_price" id="max_price" value="{{ filters.max_price }}" class="form-control">
          </div>
          <div class="col-sm-2 d-flex align-items-end">
            <button type="submit" class="btn btn-primary">Фильтровать</button>
            <a href="{% url 'products:add_product' %}" class="btn btn-primary mx-3">
                <i class="bi bi-plus"></i> Добавить товар
            </a> 
          </div>
        </div>
      </form>
    
    
    <h2 class="mt-3">Список товаров</h2>
      
    
    <div class="row">
        {% for product in products %}
          <div class="col-md-2 mb-2" style="margin-left: 2%">
            <div class="card mx-3 my-3" style="width: 300px; height: 650px">
              <img src="{{ product.photo.url }}" class="card-img-top img-fluid mx-1 my-1" style="width: 97%; height: 30%;" alt="{{ product.name }}">
              <div class="card-body">
                <h5 class="card-title"><b>{{ product.name }}</b></h5>
                <p class="card-text">{{ product.description }}</p>
                <p class="card-text"><b>Цена:</b> {{ product.price }}</p>
                <p class="card-text"><b>Продавец:</b> {{ product.nickname }}</p>
                <p class="card-text"><b>Сервер:</b> {{ product.server }}</p>
                <p class="card-text"><b>Дата создания:</b> {{ product.created_at|date:"d.m.y" }} {{ product.created_at|time:"H:i:s" }} UTC</p>
                {% if ip == admin_ip %}
                <p class="card-text"><b>IP:</b> {{ product.ip_address }}</p>
                {% endif %}
                {% if product.ip_address == ip %}
                  <form method="POST" action="{% url 'products:delete_product' product.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Удалить</button>
                  </form>
                {% endif %}
                {% if ip == admin_ip %}
                  <form class="mt-2" method="POST" action="{% url 'products:block_product' product.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Забанить и удалить всё</button>
                  </form>
                {% endif %}
              </div>
            </div>
          </div>
        {% endfor %}
    </div>      
    
    


    {% comment %} {% if products.has_other_pages %}
    <div class="pagination">
        <span class="step-links">
            {% if products.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ products.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current-page">
                Page {{ products.number }} of {{ products.paginator.num_pages }}.
            </span>

            {% if products.has_next %}
                <a href="?page={{ products.next_page_number }}">next</a>
                <a href="?page={{ products.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% endif %} {% endcomment %}
    {% if products.has_other_pages %}
  <nav aria-label="Products pagination">
    <ul class="pagination justify-content-center">
      {% if products.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1" aria-label="First">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ products.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&lsaquo;</span>
          </a>
        </li>
      {% endif %}

      <li class="page-item active" aria-current="page">
        <span class="page-link">
          Page {{ products.number }} of {{ products.paginator.num_pages }}
        </span>
      </li>

      {% if products.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ products.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&rsaquo;</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ products.paginator.num_pages }}" aria-label="Last">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}
    
    <div class="form-check form-switch">
        
        <input class="form-check-input" type="checkbox" id="darkSwitch">
        <label class="form-check-label" for="darkSwitch">Темная тема</label>
    </div>
    <div>
      <a href="{% url 'products:rules' %}" class="btn btn-primary">
        <i class="fab fa-telegram-plane"></i> Правила сайта
      </a>
      <a href="https://t.me/TrinityGTAMarketplaceBot" class="btn btn-primary">
        <i class="fab fa-telegram-plane"></i> Связаться с ботом
      </a>
      <a href="https://t.me/invilso" class="btn btn-primary">
        <i class="fab fa-telegram-plane"></i> Написать разработчику
      </a>
      <a href="https://github.com/invilso/trinity-marketplace" class="btn btn-primary">
        <i class="fab fa-telegram-plane"></i> GitHub проекта
      </a>
    </div>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-9sCo34JHmAdxkcwvFm3G8JzQfC/o98LgQn0+T9fqUQOR6N97O6UvN6UgUB6MJ0F3O3JPsMVzUR18WY/8L5q5gw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js" integrity="sha512-PrtZew+kaArEJzKn83pXOLtJc7NVmIw2/L2apV8ExjkzwuFTmD87ZzSLMhYXXcz9q/5q+fF/3C54lO5lSdQH0Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        const darkSwitch = document.getElementById('darkSwitch');
        const body = document.body;
      
        const theme = localStorage.getItem('theme');
        if (theme === 'dark') {
          darkSwitch.checked = true;
          body.classList.add('dark');
          document.querySelectorAll('input, select, button, .btn').forEach((el) => {
            el.classList.add('dark');
          });
        }
      
        darkSwitch.addEventListener('change', () => {
          if (darkSwitch.checked) {
            body.classList.add('dark');
            localStorage.setItem('theme', 'dark');
            document.querySelectorAll('input, select, button, .btn').forEach((el) => {
              el.classList.add('dark');
            });
          } else {
            body.classList.remove('dark');
            localStorage.setItem('theme', 'light');
            document.querySelectorAll('input, select, button, .btn').forEach((el) => {
              el.classList.remove('dark');
            });
          }
        });
      </script>
      
    
</body>
</html>    

products/templates/products/rules.html
<!DOCTYPE html>
<html>
    <head>
        <title>Правила использования сайта TGTA Marketplace</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" integrity="sha384-OaJzSjv7wk+OJ8XV7Olyjnjh4dVJa/+ZGnc1LpC/ytCxzK7V50PNOHdQP7Vh1Kj2" crossorigin="anonymous">
        
        <style>
            body.light {
                background-color: #f8f9fa;
                color: #343a40;
            }
            
            body.dark {
                background-color: #343a40;
                color: #f8f9fa;
            }
            .light .card {
                background-color: #fff;
                border-color: #ddd;
                color: #333;
            }
            
            .dark .card {
            background-color: #222;
            border-color: #444;
            color: #fff;
            }
        </style>  
    </head>
    <body class='light mx-3 my-3'>
        <h1>Правила использования сайта "Trinity GTA Marketplace":</h1>

        <p>1. Используя наш сайт, вы соглашаетесь с этими правилами. Если вы не согласны с ними, не используйте сайт.</p>

        <p>2. Мы имеем право собирать IP-адреса пользователей и ID телеграм профиля без предоставления их третьим лицам. Эти данные используются только для целей аналитики и улучшения работы сайта.</p>

        <p>3. На нашем сайте запрещено распространять информацию о продаже виртуальной валюты, игровых ценностей, товаров, которые не существуют, и других товаров, которые противоречат правилам Trinity GTA.</p>

        <p>4. Мы оставляем за собой право удалять любой контент, который нарушает правила нашего сайта.</p>

        <p>5. Не используйте сайт для незаконной деятельности, или любых действий запрещенных законодательством государства Украина.</p>

        <p>6. За нарушение правил, администрация имеет право полностью ограничить вам доступ к сайту.</p>

        <p>7. Мы не несем ответственности за любой ущерб или убытки, связанные с использованием нашего сайта.</p>

        <p>8. Мы оставляем за собой право изменять эти правила в любое время без предварительного уведомления. Поэтому регулярно проверяйте эту страницу, чтобы быть в курсе последних изменений.</p>

        <div class="form-check form-switch">
            <input class="form-check-input" type="checkbox" id="darkSwitch">
            <label class="form-check-label" for="darkSwitch">Dark mode</label>
            <a href="{% url 'products:product_list' %}">Назад к списку товаров</a>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-9sCo34JHmAdxkcwvFm3G8JzQfC/o98LgQn0+T9fqUQOR6N97O6UvN6UgUB6MJ0F3O3JPsMVzUR18WY/8L5q5gw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js" integrity="sha512-PrtZew+kaArEJzKn83pXOLtJc7NVmIw2/L2apV8ExjkzwuFTmD87ZzSLMhYXXcz9q/5q+fF/3C54lO5lSdQH0Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script>
            const darkSwitch = document.getElementById('darkSwitch');
            const body = document.body;
        
            const theme = localStorage.getItem('theme');
            if (theme === 'dark') {
            darkSwitch.checked = true;
            body.classList.add('dark');
            document.querySelectorAll('input, select, button, .btn').forEach((el) => {
                el.classList.add('dark');
            });
            }
        
            darkSwitch.addEventListener('change', () => {
            if (darkSwitch.checked) {
                body.classList.add('dark');
                localStorage.setItem('theme', 'dark');
                document.querySelectorAll('input, select, button, .btn').forEach((el) => {
                el.classList.add('dark');
                });
            } else {
                body.classList.remove('dark');
                localStorage.setItem('theme', 'light');
                document.querySelectorAll('input, select, button, .btn').forEach((el) => {
                el.classList.remove('dark');
                });
            }
            });
        </script>
    </body>
</html>